twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    date:
        format: d-m-Y
        timezone: Europe/Paris
when@test:
    twig:
        strict_variables: true
